name: api-ci
on:
  push: { branches: ["*"] }
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -V
      - run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt, installing minimal set"
            pip install fastapi uvicorn pydantic numpy pandas
          fi
      - run: echo "API smoke OK ✅"
